"""Render a Finding into a notice a contracting officer can act on.

House style, and the reason for it: this tool produces *screening output from
public records*, not adjudications. Every claim is attributed to a source the
KO can open, the language asks questions rather than asserting violations, and
the limitations are stated in the body rather than buried. A notice that
overstates its confidence gets the whole feed ignored — or worse, gets acted on.
"""
from __future__ import annotations

import html
from email.message import EmailMessage
from pathlib import Path

from ..models import Finding, Signal

SEVERITY_LABEL = {
    "critical": "CRITICAL", "high": "HIGH", "medium": "MEDIUM",
    "low": "LOW", "info": "INFORMATIONAL",
}

CATEGORY_LABEL = {
    "FOCI": "Foreign Ownership, Control or Influence",
    "IP_COLLATERAL": "Intellectual property pledged as collateral",
    "IP_TRANSFER": "Intellectual property transfer / distress",
    "SANCTIONS": "Sanctions and screening lists",
    "STRUCTURE": "Corporate structure and registration",
}

DISCLAIMER = (
    "This notice was generated by an automated screen of public records "
    "(USAspending.gov, FPDS-NG, SEC EDGAR, IAPD, OFAC and the contractor's own "
    "published pages). It reports correlations in public data. It is not a FOCI "
    "determination, a sanctions adjudication, or a finding of contractor "
    "non-compliance, and it has not been verified against non-public holdings. "
    "Please confirm independently before taking contractual action."
)


def has_disclaimer(text: str) -> bool:
    """Is the limitations statement still intact in `text`?

    Compared with whitespace collapsed, because the body wraps the disclaimer to
    a fixed width and indents it — an unedited notice would otherwise fail its
    own check.
    """
    def flat(value: str) -> str:
        return " ".join((value or "").split()).lower()

    return flat(DISCLAIMER) in flat(text)


def subject_for(finding: Finding) -> str:
    sev = SEVERITY_LABEL.get(finding.severity, finding.severity.upper())
    cats = sorted({s.category for s in finding.signals})
    tag = "FOCI/IP" if {"FOCI", "STRUCTURE"} & set(cats) and \
        {"IP_COLLATERAL", "IP_TRANSFER"} & set(cats) else \
        ("FOCI" if {"FOCI", "STRUCTURE"} & set(cats) else "IP")
    piids = [c.piid for c in finding.contracts if c.piid][:2]
    piid_part = f" — {', '.join(piids)}" if piids else ""
    return (f"[{sev}] {tag} screening flag: {finding.entity.name}{piid_part}")


def _fmt_money(value: float) -> str:
    if value >= 1_000_000_000:
        return f"${value / 1_000_000_000:.2f}B"
    if value >= 1_000_000:
        return f"${value / 1_000_000:.1f}M"
    return f"${value:,.0f}"


def _signal_block(sig: Signal, index: int) -> str:
    lines = [
        f"  {index}. [{SEVERITY_LABEL.get(sig.severity, sig.severity)}] {sig.title}",
        f"     Why flagged: {sig.rationale}",
    ]
    if sig.evidence:
        excerpt = " ".join(sig.evidence.split())[:400]
        lines.append(f'     Source text: "{excerpt}"')
    if sig.source_url:
        lines.append(f"     Reference:   {sig.source_url}")
    lines.append(f"     Basis:       {sig.source} | rule {sig.rule_id}"
                 f"{' | NEW since last screen' if sig.is_new else ''}")
    return "\n".join(lines)


def render_text(finding: Finding, run_id: str = "") -> str:
    officer = finding.top_officer()
    greeting = f"Dear {officer.name}," if officer.name else "Dear Contracting Officer,"
    ent = finding.entity

    parts: list[str] = [greeting, ""]
    parts.append(
        f"An automated public-records screen returned a {SEVERITY_LABEL.get(finding.severity, '')}"
        f" result for {ent.name}"
        + (f" (UEI {ent.uei})" if ent.uei else "")
        + ", which holds contract actions on which you are recorded in FPDS-NG as"
          " the responsible or last-acting contracting official."
    )
    parts.append("")

    # --- affected awards -------------------------------------------------
    parts.append("AFFECTED CONTRACT ACTIONS")
    for c in sorted(finding.contracts, key=lambda x: -x.award_amount)[:6]:
        parts.append(f"  * {c.piid or c.award_id} — {c.awarding_sub_agency or c.awarding_agency}")
        parts.append(f"    Value: {_fmt_money(c.award_amount)}   PoP: {c.start_date} to {c.end_date}")
        if c.psc_code:
            parts.append(f"    PSC {c.psc_code} {c.psc_description} | NAICS {c.naics_code}")
        if c.ip_clause_hits:
            parts.append(f"    Data rights: {'; '.join(c.ip_clause_hits[:3])}")
        if c.usaspending_url:
            parts.append(f"    {c.usaspending_url}")
    parts.append("")

    # --- what changed ----------------------------------------------------
    new = finding.new_signals
    if new:
        parts.append(f"WHAT CHANGED SINCE THE LAST SCREEN ({len(new)} new item"
                     f"{'s' if len(new) != 1 else ''})")
        for s in new[:5]:
            parts.append(f"  - {s.title} ({s.source})")
        parts.append("")

    # --- findings by category -------------------------------------------
    parts.append(f"SCREENING RESULTS  (composite score {finding.total_score};"
                 f" {len(finding.signals)} signal(s))")
    parts.append("")
    idx = 0
    for category, signals in finding.by_category().items():
        parts.append(f"{CATEGORY_LABEL.get(category, category).upper()}")
        for sig in signals[:5]:
            idx += 1
            parts.append(_signal_block(sig, idx))
            parts.append("")

    # --- suggested next steps -------------------------------------------
    parts.append("SUGGESTED VERIFICATION STEPS")
    for step in _next_steps(finding):
        parts.append(f"  - {step}")
    parts.append("")

    parts.append("LIMITATIONS")
    parts.append("  " + "\n  ".join(_wrap(DISCLAIMER, 92)))
    parts.append("")
    parts.append(f"Screening run: {run_id or finding.run_id}   Generated: {finding.generated_at}")
    if officer.source:
        parts.append(f"Addressee resolved from {officer.source} "
                     f"(confidence: {officer.confidence}). If this is not your file, "
                     f"please forward to the cognisant KO and reply so the routing "
                     f"can be corrected.")
    return "\n".join(parts)


def _next_steps(finding: Finding) -> list[str]:
    cats = {s.category for s in finding.signals}
    steps: list[str] = []
    if {"FOCI", "STRUCTURE"} & cats:
        steps.append("Confirm the contractor's current ownership chain in SAM.gov "
                     "(immediate and highest-level owner) against the entity's own "
                     "disclosures.")
        steps.append("Ask the cognisant security office (DCSA) whether a FOCI "
                     "mitigation instrument is on file and whether it covers the "
                     "transaction identified above.")
        steps.append("Verify whether a change-of-ownership notification under "
                     "32 CFR Part 117 (NISPOM) was submitted.")
    if {"IP_COLLATERAL", "IP_TRANSFER"} & cats:
        steps.append("Confirm that Government data and software rights asserted under "
                     "the award survive any security interest, and that any assertion "
                     "list on file remains accurate.")
        steps.append("Search USPTO assignment records for recorded security interests "
                     "against patents used in performance "
                     "(https://assignment.uspto.gov/patent/index.html).")
    if "SANCTIONS" in cats:
        steps.append("Adjudicate the sanctions name match against identifiers before "
                     "taking any action; name similarity alone is not a hit.")
    steps.append("If a novation, change of name, or change of control has occurred, "
                 "confirm FAR Subpart 42.12 documentation is complete.")
    return steps


def render_html(finding: Finding, run_id: str = "") -> str:
    text = render_text(finding, run_id)
    return ("<html><body style=\"font-family:-apple-system,Segoe UI,Roboto,sans-serif;"
            "font-size:14px;line-height:1.5;color:#1a1a1a\"><pre style=\"white-space:"
            "pre-wrap;font-family:inherit\">" + html.escape(text) + "</pre></body></html>")


def build_message(finding: Finding, *, sender: str, recipient: str,
                  run_id: str = "", cc: str = "") -> EmailMessage:
    msg = EmailMessage()
    msg["Subject"] = subject_for(finding)
    msg["From"] = sender or "foci-screen@localhost"
    msg["To"] = recipient
    if cc:
        msg["Cc"] = cc
    msg["X-FOCI-Run"] = run_id or finding.run_id
    msg["X-FOCI-Entity"] = finding.entity.key()
    msg["X-FOCI-Severity"] = finding.severity
    msg.set_content(render_text(finding, run_id))
    msg.add_alternative(render_html(finding, run_id), subtype="html")
    return msg


def message_from_notice(notice: dict, *, sender: str,
                        recipient: str = "") -> EmailMessage:
    """Rebuild a message from a stored notice row.

    The reviewed body is the one on the row, not a re-render of the finding: a
    reviewer may have edited the wording before approving, and the whole point
    of the approval gate is that what was approved is what goes out.
    """
    body = notice.get("body_text") or ""
    msg = EmailMessage()
    msg["Subject"] = notice.get("subject") or "FOCI/IP screening notice"
    msg["From"] = sender or "foci-screen@localhost"
    msg["To"] = recipient or notice.get("recipient") or ""
    msg["X-FOCI-Run"] = notice.get("run_id") or ""
    msg["X-FOCI-Entity"] = notice.get("entity_key") or ""
    msg["X-FOCI-Severity"] = notice.get("severity") or ""
    msg["X-FOCI-Notice"] = notice.get("notice_id") or ""
    msg.set_content(body)
    msg.add_alternative(
        "<html><body style=\"font-family:-apple-system,Segoe UI,Roboto,sans-serif;"
        "font-size:14px;line-height:1.5;color:#1a1a1a\"><pre style=\"white-space:"
        "pre-wrap;font-family:inherit\">" + html.escape(body) + "</pre></body></html>",
        subtype="html")
    return msg


def write_eml(finding: Finding, out_dir: str, *, sender: str, recipient: str,
              run_id: str = "") -> Path:
    msg = build_message(finding, sender=sender, recipient=recipient, run_id=run_id)
    safe = "".join(ch if ch.isalnum() else "_" for ch in finding.entity.name)[:48]
    path = Path(out_dir) / f"{finding.severity}_{safe}_{run_id or 'draft'}.eml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(bytes(msg))
    return path


def _wrap(text: str, width: int) -> list[str]:
    words, line, out = text.split(), "", []
    for w in words:
        if len(line) + len(w) + 1 > width:
            out.append(line)
            line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    return out
