"""Concatenate the project's Markdown and the session log into one .txt.

    python tools/bundle_docs.py
    python tools/bundle_docs.py --out foci-screen-docs.txt --no-code

One plain-text file to archive, search, or hand to someone who wants the
documentation and the reasoning behind it without cloning anything.

**Redaction is not optional here.** The session log is a transcript of a
working session, and transcripts carry whatever passed through them — API
keys pasted into a config, a Postgres URL with its password, the operator's
home directory. Every line written goes through the same patterns the session
exporter uses, and the header records that it happened, because a document
that has been edited should say so. Regenerate rather than edit; the output is
derived and is kept out of the repository.
"""
from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tools.export_session_log import REDACTIONS  # noqa: E402

# Order is the order to read them in: what it is, where it is going, how to
# deploy it, then the argument behind every decision.
DOCUMENTS = [
    ("README.md", "What the tool does, what it reads, and why it is built this way"),
    ("ROADMAP.md", "What is built, what is next, and what was deliberately not done"),
    ("DEPLOY.md", "Getting it onto GitHub and Render, and what breaks there"),
    ("docs/SESSION_LOG.md", "The build conversation: every prompt and reply, in order"),
]
CODE_BUNDLE = ("foci-screen-all-code.md", "Every source file, generated by bundle_source.py")

RULE = "=" * 78


def redact(text: str) -> str:
    for pattern, replacement in REDACTIONS:
        text = pattern.sub(replacement, text)
    return text


def commit() -> str:
    try:
        return subprocess.run(["git", "-C", str(ROOT), "log", "-1", "--oneline"],
                              capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="foci-screen-docs.txt")
    ap.add_argument("--no-code", action="store_true",
                    help="leave out the generated full-source bundle")
    args = ap.parse_args()

    wanted = list(DOCUMENTS) + ([] if args.no_code else [CODE_BUNDLE])
    present = [(name, blurb) for name, blurb in wanted if (ROOT / name).is_file()]
    missing = [name for name, _ in wanted if not (ROOT / name).is_file()]

    out: list[str] = []
    out.append(RULE)
    out.append("foci-screen — documentation and build history")
    out.append(RULE)
    out.append("")
    out.append(f"Generated {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC "
               f"from commit {commit()}.")
    out.append("")
    out.append("Secrets, credentials and home directory paths have been replaced with")
    out.append("placeholders such as <redacted-api-key>. This file is generated —")
    out.append("regenerate it with tools/bundle_docs.py rather than editing it.")
    out.append("")
    out.append("CONTENTS")
    for i, (name, blurb) in enumerate(present, 1):
        out.append(f"  {i}. {name}")
        out.append(f"     {blurb}")
    if missing:
        out.append("")
        out.append("  Not found, and so not included: " + ", ".join(missing))
    out.append("")

    for i, (name, blurb) in enumerate(present, 1):
        body = (ROOT / name).read_text(encoding="utf-8", errors="replace")
        out.append("")
        out.append(RULE)
        out.append(f"{i}. {name}")
        out.append(f"   {blurb}")
        out.append(f"   {len(body.splitlines()):,} lines")
        out.append(RULE)
        out.append("")
        out.append(body.rstrip())
        out.append("")

    text = redact("\n".join(out)) + "\n"
    target = ROOT / args.out
    target.write_text(text, encoding="utf-8")

    kb = len(text.encode("utf-8")) / 1024
    print(f"wrote {target.name}  ({kb:,.0f} KB, {len(text.splitlines()):,} lines)")
    for name, _ in present:
        print(f"  included {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
